name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Install dependencies
      - run: npm ci

      # Build and output bundle stats to webpack-stats.json
      - run: npm run build
        env:
          RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}

      # Send bundle stats and build information to RelativeCI
      # - name: Send bundle stats to RelativeCI
      #   uses: relative-ci/agent-action@v2
      #   with:
      #     webpackStatsFile: ./webpack-stats.json
      #     key: ${{ secrets.RELATIVE_CI_KEY }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
